---
- hosts: ctrl
  become: true
  gather_facts: true

  tasks:
    
    # STEP 13: Init cluster

    - name: Check if cluster is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kube_conf

    - name: Initialize Kubernetes cluster using kubeadm
      command: >
        kubeadm init
        --apiserver-advertise-address=192.168.56.100
        --node-name ctrl
        --pod-network-cidr=10.244.0.0/16
      when: not kube_conf.stat.exists
      register: kube_init_output

    # STEP 14: Setup kubectl
    
    - name: Create .kube directory for vagrant user
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy admin.conf to vagrant user config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Copy kubeconfig to shared folder (for host access)
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /vagrant/kubeconfig
        remote_src: yes
        mode: '0644'

    # Step 15: Install Flannel Pod Network
    - name: Copy Flannel manifest
      copy:
        src: files/kube-flannel.yml
        dest: /tmp/kube-flannel.yml
      tags: [ 'flannel' ]

    - name: Apply Flannel network
      become_user: vagrant
      shell: kubectl apply -f /tmp/kube-flannel.yml
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      tags: [ 'flannel' ]
    # STEP 16: Install Helm

    - name: Install Helm prerequisites
      apt:
        name:
          - curl
          - gpg
          - apt-transport-https
        state: present

    - name: Download and dearmor Helm GPG key
      shell: |
        curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor -o /usr/share/keyrings/helm.gpg
      args:
        creates: /usr/share/keyrings/helm.gpg

    - name: Add Helm apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
        filename: "helm-stable-debian"
        state: present
        update_cache: yes

    - name: Install Helm
      apt:
        name: helm
        state: present

    # STEP 17: Install Helm package (diff)

    - name: Install helm-diff plugin
      become_user: vagrant
      shell: helm plugin install https://github.com/databus23/helm-diff
      register: helm_plugin_result
      failed_when: 
        - helm_plugin_result.rc != 0 
        - '"plugin already exists" not in helm_plugin_result.stderr'
      changed_when: '"Installed" in helm_plugin_result.stdout'
