---
- hosts: all
  become: true

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:

    - name: Download MetalLB native manifest
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        dest: /tmp/metallb-native.yaml

    - name: Apply MetalLB manifest
      shell: kubectl apply -f /tmp/metallb-native.yaml

    - name: Wait for MetalLB controller to be ready
      shell: >
        kubectl wait --namespace metallb-system
        --for=condition=ready pod
        --selector=app=metallb
        --timeout=90s
      register: metallb_wait
      retries: 10
      delay: 10
      until: metallb_wait.rc == 0

    - name: Copy MetalLB Pool Configuration
      copy:
        src: files/metallb-config.yaml
        dest: /tmp/metallb-config.yaml

    - name: Apply MetalLB Pool Configuration
      shell: kubectl apply -f /tmp/metallb-config.yaml
    
    - name: Add Nginx Ingress Helm Repo
      shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      register: helm_repo_add
      failed_when: false
      changed_when: "'already exists' not in helm_repo_add.stderr"

    - name: Update Helm repos
      shell: helm repo update

    - name: Install Nginx Ingress with Fixed IP
      shell: |
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx \
          --create-namespace \
          --set controller.service.loadBalancerIP=192.168.56.90

    - name: Wait for Nginx Ingress Controller to be ready
      shell: >
        kubectl wait --namespace ingress-nginx
        --for=condition=ready pod
        --selector=app.kubernetes.io/component=controller
        --timeout=120s
      register: ingress_wait
      retries: 5
      delay: 10
      until: ingress_wait.rc == 0

    # Step 22: Install Kubernetes Dashboard
    - name: Add Kubernetes Dashboard Helm repository
      shell: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
      register: helm_repo_add_dashboard
      failed_when: false
      changed_when: "'already exists' not in helm_repo_add_dashboard.stderr"

    - name: Update Helm repositories
      shell: helm repo update

    # Not the latest version due to authorization issues with newer releases
    - name: Install Kubernetes Dashboard (older stable version)
      shell: |
        helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard \
          --namespace kubernetes-dashboard \
          --create-namespace \
          --version 6.0.8
      register: dashboard_install

    - name: Wait for Dashboard pods to be ready
      shell: >
        kubectl wait --namespace kubernetes-dashboard
        --for=condition=ready pod
        --selector=app.kubernetes.io/name=kubernetes-dashboard
        --timeout=120s
      register: dashboard_wait
      retries: 5
      delay: 10
      until: dashboard_wait.rc == 0

    - name: Create Dashboard admin user manifest
      copy:
        dest: /tmp/dashboard-admin.yaml
        content: |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kubernetes-dashboard
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: admin-user-token
            namespace: kubernetes-dashboard
            annotations:
              kubernetes.io/service-account.name: admin-user
          type: kubernetes.io/service-account-token

    - name: Apply Dashboard admin user
      shell: kubectl apply -f /tmp/dashboard-admin.yaml

    - name: Wait for admin user token to be created
      shell: kubectl get secret admin-user-token -n kubernetes-dashboard
      register: token_check
      retries: 10
      delay: 3
      until: token_check.rc == 0

    - name: Ensure certificate directory exists
      file:
        path: /etc/kubernetes/certs
        state: directory
        mode: '0755'

    - name: Copy Dashboard SSL Certificate
      copy:
        src: files/certs/dashboard.crt
        dest: /etc/kubernetes/certs/dashboard.crt
        mode: '0644'

    - name: Copy Dashboard SSL Key
      copy:
        src: files/certs/dashboard.key
        dest: /etc/kubernetes/certs/dashboard.key
        mode: '0600'

    - name: Create TLS secret for dashboard
      shell: |
        kubectl create secret tls dashboard-tls \
          --cert=/etc/kubernetes/certs/dashboard.crt \
          --key=/etc/kubernetes/certs/dashboard.key \
          --namespace kubernetes-dashboard \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Create Dashboard Ingress manifest with HTTPS
      copy:
        dest: /tmp/dashboard-ingress.yaml
        content: |
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: kubernetes-dashboard
            namespace: kubernetes-dashboard
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/ssl-passthrough: "false"
          spec:
            ingressClassName: nginx
            tls:
            - hosts:
              - dashboard.local
              secretName: dashboard-tls
            rules:
            - host: dashboard.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kubernetes-dashboard
                      port:
                        number: 443

    - name: Apply Dashboard Ingress
      shell: kubectl apply -f /tmp/dashboard-ingress.yaml

    # Step 23: Install Istio
    - name: Check for Istio download
      stat:
        path: /home/vagrant/istio-1.25.2
      register: istio_dir

    - name: Download Istio
      shell: |
        cd /home/vagrant
        curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.25.2 sh -
      when: not istio_dir.stat.exists

    - name: Add istioctl to PATH for vagrant user
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'export PATH=$PATH:/home/vagrant/istio-1.25.2/bin'
        create: yes

    - name: Check for Itio installation
      shell: kubectl get namespace istio-system
      register: istio_namespace
      failed_when: false
      changed_when: false

    - name: Create Istio configuration with fixed IP
      copy:
        dest: /tmp/istio-config.yaml
        content: |
          apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          spec:
            components:
              ingressGateways:
              - name: istio-ingressgateway
                enabled: true
                k8s:
                  service:
                    loadBalancerIP: 192.168.56.91
      when: istio_namespace.rc != 0

    - name: Install Istio with configuration
      shell: /home/vagrant/istio-1.25.2/bin/istioctl install -y -f /tmp/istio-config.yaml
      when: istio_namespace.rc != 0

    - name: Wait for Istio ingress gateway to be ready
      shell: >
        kubectl wait --namespace istio-system
        --for=condition=ready pod
        --selector=app=istio-ingressgateway
        --timeout=120s
      register: istio_wait
      retries: 5
      delay: 10
      until: istio_wait.rc == 0