---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update Apt Cache (Only if older than 1 hour)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: ['setup']

    - name: Install Common Utilities
      apt:
        name:
          - curl
          - wget
          - git
          - htop
        state: present
      tags: ['setup']

    - name: Add cluster nodes to /etc/hosts
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        content: |
          {{ ctrl_ip }} ctrl
          {% for i in range(1, worker_count | int + 1) %}
          {{ subnet_prefix }}.{{ 100 + i }} node-{{ i }}
          {% endfor %}

    - name: Register public keys
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ query('fileglob', 'ssh-keys/*.pub') }}"
      tags: ['ssh-keys']

    - name: Create k8s.conf to load modules at boot
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: Load overlay module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Enable bridged IPv4 iptables processing
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: yes

    - name: Enable bridged IPv6 iptables processing
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: '1'
        state: present
        reload: yes
